#!/usr/bin/env python3
"""
DNS RPZ Manager - RPZ Zone File Generator

This script generates the RPZ zone file from the database.
It can be run from cron or called from the application.
"""

import asyncio
import sys
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Dict, Any

# Add the parent directory to the path
sys.path.insert(0, str(Path(__file__).parent.parent))

from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import sessionmaker

from app.core.config import settings


class RPZGenerator:
    """Generates RPZ zone files from database entries."""
    
    def __init__(self):
        self.engine = create_async_engine(settings.DATABASE_URL, echo=False)
        self.async_session = sessionmaker(
            self.engine, class_=AsyncSession, expire_on_commit=False
        )
    
    async def get_active_domains(self) -> List[Dict[str, Any]]:
        """Fetch all active domains from the database."""
        async with self.async_session() as session:
            try:
                result = await session.execute(
                    text(
                        """
                        SELECT id, domain, action, reason, source, created_at, updated_at
                        FROM domains
                        WHERE is_active = true
                        ORDER BY domain
                        """
                    )
                )
                rows = result.mappings()
                return [dict(row) for row in rows]
            except Exception as e:
                print(f"Error fetching domains: {e}")
                raise
            finally:
                await session.close()
    
    def format_soa_serial(self) -> str:
        """Generate SOA serial number in YYYYMMDDNN format."""
        now = datetime.now(timezone.utc)
        return now.strftime("%Y%m%d") + "01"
    
    def generate_zone_record(self, domain: str, action: str, reason: str = "") -> str:
        """Generate a single RPZ zone record."""
        # Clean domain name
        domain = domain.strip().lower()
        if domain.startswith("."):
            domain = domain[1:]
        
        # Map actions to RPZ responses
        action_map = {
            "nxdomain": f"{domain} CNAME .\n",
            "nodata": f"{domain} CNAME *. \n",
            "passthru": f"{domain} CNAME rpz-passthru.\n",
            "drop": f"{domain} CNAME rpz-drop.\n",
            "nodrop": f"{domain} CNAME rpz-notrimpt.\n",
            "tcp-only": f"{domain} CNAME rpz-tcp-only.\n",
        }
        
        # Default to NXDOMAIN if action not recognized
        record = action_map.get(action, f"{domain} CNAME .\n")
        
        # Add comment with reason and metadata
        if reason:
            comment = f"; Reason: {reason}\n"
            record = comment + record
        
        return record
    
    def generate_zone_file(self, domains: List[Dict[str, Any]]) -> str:
        """Generate the complete RPZ zone file content."""
        serial = self.format_soa_serial()
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        
        # Build zone file content
        zone_content = f"""$TTL 86400
@ IN SOA localhost. hostmaster.rpz. (
    {serial}     ; Serial (YYYYMMDDNN)
    3600        ; Refresh (1 hour)
    900         ; Retry (15 minutes)
    2419200     ; Expire (4 weeks)
    7200        ; Negative Cache TTL (2 hours)
)

; Name Servers
    IN NS localhost.

; =============================================================================
; RPZ Zone - DNS Response Policy Zone
; Generated by DNS RPZ Manager
; Generation Time: {now}
; Total Rules: {len(domains)}
; =============================================================================

; Active RPZ Rules
"""
        
        # Group domains by action for better organization
        domains_by_action = {}
        for domain in domains:
            action = domain.get("action", "nxdomain")
            if action not in domains_by_action:
                domains_by_action[action] = []
            domains_by_action[action].append(domain)
        
        # Write rules grouped by action
        action_comments = {
            "nxdomain": "NXDOMAIN - Return NXDOMAIN (Domain does not exist)",
            "nodata": "NODATA - Return empty answer",
            "passthru": "PASSTHRU - Allow domain (whitelist)",
            "drop": "DROP - Silently drop the query",
            "nodrop": "NODROP - Do not drop (not truncated)",
            "tcp-only": "TCP-ONLY - Force TCP for this domain",
        }
        
        for action, action_domains in domains_by_action.items():
            comment = action_comments.get(action, f"Action: {action}")
            zone_content += f"\n; {comment}\n"
            
            for domain_info in action_domains:
                domain = domain_info["domain"]
                reason = domain_info.get("reason", "")
                record = self.generate_zone_record(domain, action, reason)
                zone_content += record
        
        # Add footer
        zone_content += f"\n; End of RPZ zone file\n"
        zone_content += f"; Generated: {now}\n"
        zone_content += f"; Total blocked domains: {len(domains)}\n"
        
        return zone_content
    
    async def generate_and_write_zone(self, output_path: str = None) -> bool:
        """Generate the RPZ zone file and write it to disk."""
        try:
            # Get active domains
            print("Fetching active domains from database...")
            domains = await self.get_active_domains()
            print(f"Found {len(domains)} active domains.")
            
            # Generate zone content
            print("Generating RPZ zone file...")
            zone_content = self.generate_zone_file(domains)
            
            # Determine output path
            if output_path is None:
                output_path = settings.BIND_RPZ_PATH
            
            # Ensure directory exists
            output_dir = Path(output_path).parent
            output_dir.mkdir(parents=True, exist_ok=True)
            
            # Write zone file
            print(f"Writing zone file to: {output_path}")
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(zone_content)
            
            print(f"RPZ zone file generated successfully!")
            print(f"  - Domains: {len(domains)}")
            print(f"  - Output: {output_path}")
            print(f"  - Size: {os.path.getsize(output_path)} bytes")
            
            return True
        
        except Exception as e:
            print(f"Error generating RPZ zone file: {e}")
            return False
    
    async def validate_zone_file(self, zone_path: str = None) -> bool:
        """Validate the generated zone file using named-checkzone."""
        try:
            if zone_path is None:
                zone_path = settings.BIND_RPZ_PATH
            
            # Try to use named-checkzone if available
            import subprocess
            
            result = subprocess.run(
                ["named-checkzone", settings.RPZ_ZONE_NAME, zone_path],
                capture_output=True,
                text=True,
                timeout=30,
            )
            
            if result.returncode == 0:
                print("Zone file validation passed!")
                return True
            else:
                print(f"Zone file validation failed: {result.stderr}")
                return False
        
        except FileNotFoundError:
            print("named-checkzone not found. Skipping validation.")
            return True
        except subprocess.TimeoutExpired:
            print("Zone file validation timed out.")
            return False
        except Exception as e:
            print(f"Error validating zone file: {e}")
            return False
    
    async def close(self):
        """Close the database connection."""
        await self.engine.dispose()


async def main():
    """Main function."""
    print("=" * 60)
    print("DNS RPZ Manager - RPZ Zone File Generator")
    print("=" * 60)
    
    generator = RPZGenerator()
    
    try:
        # Parse command line arguments
        output_path = None
        validate = True
        
        if len(sys.argv) > 1:
            output_path = sys.argv[1]
        if len(sys.argv) > 2 and sys.argv[2] == "--no-validate":
            validate = False
        
        # Generate zone file
        success = await generator.generate_and_write_zone(output_path)
        
        if not success:
            sys.exit(1)
        
        # Validate zone file if requested
        if validate:
            print("\nValidating zone file...")
            await generator.validate_zone_file(output_path)
        
        print("\n" + "=" * 60)
        print("RPZ zone file generation completed successfully!")
        print("=" * 60)
        
        # Reload BIND9 if rndc is available
        try:
            import subprocess
            result = subprocess.run(
                ["rndc", "reload", "rpz"],
                capture_output=True,
                text=True,
                timeout=10,
            )
            if result.returncode == 0:
                print("BIND9 RPZ zone reloaded successfully!")
            else:
                print(f"Warning: Could not reload BIND9: {result.stderr}")
        except FileNotFoundError:
            print("Note: rndc not found. You may need to manually reload BIND9.")
        except Exception as e:
            print(f"Note: Could not reload BIND9: {e}")
    
    except Exception as e:
        print(f"\nError: {e}")
        sys.exit(1)
    
    finally:
        await generator.close()


if __name__ == "__main__":
    asyncio.run(main())
